name: "mediapulse_analytics"
version: "1.0.0"
config-version: 2

profile: "mediapulse_analytics"

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]
docs-paths:     ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: "RAW"

# ---------------------------------------------------------------------------
# Model materialisation defaults
# ---------------------------------------------------------------------------
models:
  mediapulse_analytics:
    staging:
      +materialized: view
      crm:
        +group: crm
      streamview_legacy:
        +group: streaming
    intermediate:
      int_adv_rep_touchpoint_cumcounts:
        +group: crm
      int_streamview_legacy__watch_events:
        +group: streaming
    marts:
      +materialized: table
      crm:
        +group: crm
      streamview_legacy:
        +group: streaming


snapshots:
  mediapulse_analytics:
    +target_schema: snapshots
